shell = "zsh"

# 補完を増やす
[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

# 入力中のコマンドを色付けする（標準の syntax-highlighting より速い版）
[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"

# 履歴からの予測を灰色で出す
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

