"$schema" = "https://starship.rs/config-schema.json"

add_newline = true
continuation_prompt = "▶▶ "
scan_timeout = 30
command_timeout = 1000

format = """
$username$hostname$directory$git_branch$git_status$docker_context$cmd_duration$status
$line_break$character"""

[cmd_duration]
min_time = 2_000
format = "took [$duration]($style) "
style = "yellow italic"

[directory]
style = "bold cyan"
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 4
truncate_to_repo = true
truncation_symbol = "…/"
read_only = " "
read_only_style = "bold yellow"

[character]
success_symbol = "[>](bold green) "
error_symbol = "[>](bold red) "
vicmd_symbol = "[<](bold yellow) "

[git_branch]
symbol = " "
style = "bold magenta"
format = "on [$symbol$branch]($style) "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold yellow"
conflicted = "="
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = "\\$${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"

[docker_context]
symbol = " "
format = "via [$symbol$context]($style) "
style = "blue"
only_with_files = true

[status]
disabled = false
format = "[✘ $status]($style) "
style = "bold red"
success_symbol = ""
map_symbol = true
recognize_signal_code = true

[hostname]
ssh_only = true
format = "[@$hostname](dimmed green) "
disabled = false

[username]
show_always = false
style_user = "dimmed green"
style_root = "bold red"
format = "[$user]($style)@"
disabled = false

[package]
disabled = true

[os]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true

[azure]
disabled = true

